IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 335
  ROI_HEIGHT: 40

XYCAR:
  START_SPEED: 0.0
  MAX_SPEED: 21.0
  MIN_SPEED: 10.0
  SPEED_CONTROL_THRESHOLD: 10.0
  ACCELERATION_STEP: 0.25
  DECELERATION_STEP: 0.15

PID:
  P_GAIN: 0.34
  I_GAIN: 0.00065
  D_GAIN: 0.01

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 150
  HIGH_THRESHOLD: 250

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 20
  MIN_LINE_LENGTH: 15
  MAX_LINE_GAP: 6

DEBUG: True
